module.exports =  {
	"awardsList": [{
		"id": 6,
		"title": "2018年度大禹水利科学技术奖通过形式审查申报项目的公示",
		"content": null,
		"date": null,
		"appendix": null,
		"type": 0
	}, {
		"id": 3,
		"title": "关于推荐大禹水利科学技术奖评审专家的通知",
		"content": null,
		"date": null,
		"appendix": null,
		"type": 0
	}, {
		"id": 1,
		"title": "2017年度大禹水利科学技术奖励公示",
		"content": null,
		"date": null,
		"appendix": null,
		"type": 0
	}, {
		"id": 4,
		"title": "2013年度大禹水利科学技术奖励公示",
		"content": null,
		"date": null,
		"appendix": null,
		"type": 0
	}, {
		"id": 5,
		"title": "关于2013年度大禹水利科学技术奖推荐获奖项目答辩的通知",
		"content": null,
		"date": null,
		"appendix": null,
		"type": 0
	}],
	"Result": "success"
}